//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraoDoiDo
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoDich
    {
        public int IdGiaoDich { get; set; }
        public int IdNguoiDung { get; set; }
        public string LoaiGiaoDich { get; set; }
        public string SoTien { get; set; }
        public string TuNguonGiaoDich { get; set; }
        public string DenNguonGiaoDich { get; set; }
        public string NgayGiaoDich { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
