//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraoDoiDo
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiDung()
        {
            this.DanhGiaNguoiDang = new HashSet<DanhGiaNguoiDang>();
            this.DanhGiaNguoiDang1 = new HashSet<DanhGiaNguoiDang>();
            this.DanhMucYeuThich = new HashSet<DanhMucYeuThich>();
            this.GiaoDich = new HashSet<GiaoDich>();
            this.GioHang = new HashSet<GioHang>();
            this.NguoiDungVoucher = new HashSet<NguoiDungVoucher>();
            this.QuanLyDonHang = new HashSet<QuanLyDonHang>();
            this.QuanLyDonHang1 = new HashSet<QuanLyDonHang>();
            this.SanPham = new HashSet<SanPham>();
            this.TrangThaiDonHang = new HashSet<TrangThaiDonHang>();
        }
        


        public int IdNguoiDung { get; set; }
        public string HoTenNguoiDung { get; set; }
        public string GioiTinhNguoiDung { get; set; }
        public string NgaySinhNguoiDung { get; set; }
        public string CMNDNguoiDung { get; set; }
        public string EmailNguoiDung { get; set; }
        public string SdtNguoiDung { get; set; }
        public string DiaChiNguoiDung { get; set; }
        public string AnhNguoiDung { get; set; }
        public string TienNguoiDung { get; set; }
        public string TuKhoaSanPhamDangQuanTam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaNguoiDang> DanhGiaNguoiDang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaNguoiDang> DanhGiaNguoiDang1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhMucYeuThich> DanhMucYeuThich { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaoDich> GiaoDich { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NguoiDungVoucher> NguoiDungVoucher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuanLyDonHang> QuanLyDonHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuanLyDonHang> QuanLyDonHang1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPham { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrangThaiDonHang> TrangThaiDonHang { get; set; }
    }
}
