//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraoDoiDo
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiDung()
        {
            this.DanhGiaNguoiDangs = new HashSet<DanhGiaNguoiDang>();
            this.DanhGiaNguoiDangs1 = new HashSet<DanhGiaNguoiDang>();
            this.DanhMucYeuThiches = new HashSet<DanhMucYeuThich>();
            this.GiaoDiches = new HashSet<GiaoDich>();
            this.GioHangs = new HashSet<GioHang>();
            this.NguoiDungVouchers = new HashSet<NguoiDungVoucher>();
            this.QuanLyDonHangs = new HashSet<QuanLyDonHang>();
            this.QuanLyDonHangs1 = new HashSet<QuanLyDonHang>();
            this.SanPhams = new HashSet<SanPham>();
            this.TrangThaiDonHangs = new HashSet<TrangThaiDonHang>();
        }
    
        public int IdNguoiDung { get; set; }
        public string HoTenNguoiDung { get; set; }
        public string GioiTinhNguoiDung { get; set; }
        public string NgaySinhNguoiDung { get; set; }
        public string CMNDNguoiDung { get; set; }
        public string EmailNguoiDung { get; set; }
        public string SdtNguoiDung { get; set; }
        public string DiaChiNguoiDung { get; set; }
        public string AnhNguoiDung { get; set; }
        public string TienNguoiDung { get; set; }
        public string TuKhoaSanPhamDangQuanTam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaNguoiDang> DanhGiaNguoiDangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaNguoiDang> DanhGiaNguoiDangs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhMucYeuThich> DanhMucYeuThiches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaoDich> GiaoDiches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NguoiDungVoucher> NguoiDungVouchers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuanLyDonHang> QuanLyDonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuanLyDonHang> QuanLyDonHangs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPhams { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrangThaiDonHang> TrangThaiDonHangs { get; set; }
    }
}
