//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraoDoiDo
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDungVoucher
    {
        public int IdNguoiDung { get; set; }
        public int IdVoucher { get; set; }
        public string Dung { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
