//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraoDoiDo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.DanhMucYeuThiches = new HashSet<DanhMucYeuThich>();
            this.GioHangs = new HashSet<GioHang>();
            this.MoTaAnhSanPhams = new HashSet<MoTaAnhSanPham>();
            this.QuanLyDonHangs = new HashSet<QuanLyDonHang>();
            this.TrangThaiDonHangs = new HashSet<TrangThaiDonHang>();
        }
    
        public int IdSanPham { get; set; }
        public Nullable<int> IdNguoiDang { get; set; }
        public string Ten { get; set; }
        public string LinkAnhBia { get; set; }
        public string Loai { get; set; }
        public string SoLuong { get; set; }
        public string SoLuongDaBan { get; set; }
        public string GiaGoc { get; set; }
        public string GiaBan { get; set; }
        public string PhiShip { get; set; }
        public string TrangThai { get; set; }
        public string NoiBan { get; set; }
        public string XuatXu { get; set; }
        public string NgayMua { get; set; }
        public string PhanTramMoi { get; set; }
        public string MoTaChung { get; set; }
        public string SoLuotXem { get; set; }
        public string NgayDang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhMucYeuThich> DanhMucYeuThiches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoTaAnhSanPham> MoTaAnhSanPhams { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuanLyDonHang> QuanLyDonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrangThaiDonHang> TrangThaiDonHangs { get; set; }
    }
}
