//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraoDoiDo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TraoDoiDoEntities : DbContext
    {
        public TraoDoiDoEntities()
            : base("name=TraoDoiDoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DanhGiaNguoiDang> DanhGiaNguoiDang { get; set; }
        public virtual DbSet<DanhMucYeuThich> DanhMucYeuThich { get; set; }
        public virtual DbSet<GiaoDich> GiaoDich { get; set; }
        public virtual DbSet<GioHang> GioHang { get; set; }
        public virtual DbSet<MoTaAnhSanPham> MoTaAnhSanPham { get; set; }
        public virtual DbSet<NguoiDung> NguoiDung { get; set; }
        public virtual DbSet<NguoiDungVoucher> NguoiDungVoucher { get; set; }
        public virtual DbSet<QuanLyDonHang> QuanLyDonHang { get; set; }
        public virtual DbSet<SanPham> SanPham { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoan { get; set; }
        public virtual DbSet<TrangThaiDonHang> TrangThaiDonHang { get; set; }
        public virtual DbSet<Voucher> Voucher { get; set; }
    }
}
