//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraoDoiDo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voucher()
        {
            this.NguoiDungVoucher = new HashSet<NguoiDungVoucher>();
        }
    
        public int IdVoucher { get; set; }
        public string TenVoucher { get; set; }
        public string GiaTri { get; set; }
        public string SoLuotSuDungToiDa { get; set; }
        public string SoLuotDaSuDung { get; set; }
        public string NgayBatDau { get; set; }
        public string NgayKetThuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NguoiDungVoucher> NguoiDungVoucher { get; set; }
    }
}
